version: "3.9"

services:

  web-app:
    container_name: web-app
    image: ${REGISTRY}/web-app
    build:
      context: ./services/web-app
      dockerfile: ${BUILD_MODE}.dockerfile
    volumes:
      - ./services/web-app:/app
    environment:
      VITE_RTMP_URL: "localhost:3010"
      VITE_HLS_URL: "localhost:3011"
      VITE_USERS_URL: "localhost:8000/users"
      VITE_ROOMS_URL: "localhost:8000/rooms"
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - rtmp

  rtmp:
    container_name: rtmp
    image: ${REGISTRY}/rtmp
    build: ./services/rtmp
    volumes:
      - ./services/rtmp/data/hls:/tmp/hls
    ports:
      - 3010:1935
      - 3011:8080
    depends_on:
      - rooms

  # ==========================================================================

  revers-proxy:
    container_name: revers-proxy
    image: ${REGISTRY}/revers-proxy
    build: ./services/revers-proxy
    ports:
      - 8000:80
    depends_on:
      - users
      - rooms

  # ==========================================================================

  users:
    container_name: users
    image: ${REGISTRY}/users
    build: ./services/users
    environment:
      USERS_HTTP_PORT: "8010"
      USERS_GRPC_PORT: "8011"
      USERS_MONGO_URL: "mongodb://users-db:27017/"
      USERS_DATABASE_TIMEOUT: "10s"
      USERS_SESSION_LENGTH: "720m"
    ports:
      - 8010:8010
      - 8011:8011
    command: ./service
    depends_on:
      - users-db

  rooms:
    container_name: rooms
    image: ${REGISTRY}/rooms
    build: ./services/rooms
    environment:
      ROOMS_HTTP_PORT: "8020"
      ROOMS_HTTP_PONG_TIMEOUT: "30s"
      ROOMS_USERS_GRPC_URL: "users:8011"
      ROOMS_REDIS_URL: "rooms-cache:6379"
      ROOMS_REDIS_PASSW: ""
    ports:
      - 8020:8020
    command: ./service
    depends_on:
      - rooms-cache

  # ==========================================================================

  users-db:
    container_name: users-db
    image: ${REGISTRY}/users-db
    build: ./services/users-db
    ports:
      - 27017:27017

  rooms-cache:
    container_name: rooms-cache
    image: ${REGISTRY}/rooms-cache
    build: ./services/rooms-cache
    ports:
      - 6379:6379
