version: "3"

services:

  web_app:
    container_name: web_app
    image: node:lts
    working_dir: /app
    volumes:
      - ./src/web-app:/app
    environment:
      VITE_MICROSERVICES_URL: "http://localhost:8000"
      VITE_RTMP_URL: "http://localhost:8000"
    ports:
      - 5173:5173
    command: ["npm", "run", "dev"]
    depends_on:
      - revers_proxy
      - rtmp

  revers_proxy:
    container_name: revers_proxy
    image: nginx:1.17.10
    volumes:
      - ./revers_proxy/dev/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8001:80
    depends_on:
      - rooms

  rtmp:
    container_name: rtmp
    image: tiangolo/nginx-rtmp
    volumes:
      - ./rtmp/dev/nginx.conf:/etc/nginx/nginx.conf
      - ./rtmp/dev/data/hls:/tmp/hls
    ports:
      - 8002:1935
      - 8003:8080
    depends_on:
      - rooms

  rooms:
    container_name: rooms
    image: golang:latest
    working_dir: /app
    volumes:
      - ./src/microservices/rooms:/app
    ports:
      - 8020:8020
    command: go run main.go
