services:

  users:
    container_name: users
    image: golive/users
    build:
      context: ./services/users
      dockerfile: Dockerfile
    ports:
      - 8100:8000
      - 8101:8001
    command: ./app
    depends_on:
      - users-db

  users-db:
    container_name: users-db
    image: postgres:18
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 8199:5432
