version: "3"

services:

  web_app:
    container_name: web_app
    build:
      context: ./src/web-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./src/web-app:/app
    environment:
      VITE_MICROSERVICES_URL: "localhost:8001"
      VITE_RTMP_URL: "localhost:8002"
      VITE_HLS_URL: "localhost:8003"
    ports:
      - 5173:5173
    command: npm run dev
    depends_on:
      - revers_proxy
      - rtmp

  # ==========================================================================

  revers_proxy:
    container_name: revers_proxy
    build: ./revers_proxy/dev
    ports:
      - 8001:80
    depends_on:
      - users
      - rooms

  rtmp:
    container_name: rtmp
    build: ./rtmp/dev
    volumes:
      - ./rtmp/dev/data/hls:/tmp/hls
    ports:
      - 8002:1935
      - 8003:8080
    depends_on:
      - rooms

  # ==========================================================================

  users:
    container_name: users
    build:
      context: ./src/microservices/users
      dockerfile: Dockerfile.dev
    environment:
      USERS_HTTP_PORT: "8010"
      USERS_GRPC_PORT: "8011"

      USERS_MONGO_URL: "mongodb://users_db:27017/"

      USERS_DATABASE_TIMEOUT: "10s"
      USERS_SESSION_LENGTH: "720m"
    ports:
      - 8010:8010
      - 8011:8011
    command: ./service
    depends_on:
      - users_db

  users_db:
    container_name: users_db
    image: mongo:latest
    ports:
      - 27017:27017

  # ==========================================================================

  rooms:
    container_name: rooms
    build:
      context: ./src/microservices/rooms
      dockerfile: Dockerfile.dev
    environment:
      ROOMS_HTTP_PORT: "8020"
      ROOMS_HTTP_PONG_TIMEOUT: "30s"

      ROOMS_USERS_GRPC_URL: "users:8011"
      ROOMS_REDIS_URL: "rooms_cache:6379"
      ROOMS_REDIS_PASSW: ""
    ports:
      - 8020:8020
    command: ./service
    depends_on:
      - rooms_cache

  rooms_cache:
    container_name: rooms_cache
    image: redislabs/redismod
    ports:
      - 6379:6379
