version: "3.9"

services:

  web_app:
    container_name: web_app
    build:
      context: ./services/web-app
      dockerfile: Dockerfile.dev
    volumes:
      - ./services/web-app:/app
    environment:
      VITE_RTMP_URL: "localhost:3010"
      VITE_HLS_URL: "localhost:3011"
      VITE_USERS_URL: "localhost:8000/users"
      VITE_ROOMS_URL: "localhost:8000/rooms"
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
      - rtmp

  rtmp:
    container_name: rtmp
    build: ./services/rtmp
    volumes:
      - ./services/rtmp/data/hls:/tmp/hls
    ports:
      - 3010:1935
      - 3011:8080
    depends_on:
      - rooms

  # ==========================================================================

  revers_proxy:
    container_name: revers_proxy
    build: ./services/revers_proxy
    ports:
      - 8000:80
    depends_on:
      - users
      - rooms

  # ==========================================================================

  users:
    container_name: users
    build: ./services/users
    environment:
      USERS_HTTP_PORT: "8010"
      USERS_GRPC_PORT: "8011"

      USERS_MONGO_URL: "mongodb://users_db:27017/"

      USERS_DATABASE_TIMEOUT: "10s"
      USERS_SESSION_LENGTH: "720m"
    ports:
      - 8010:8010
      - 8011:8011
    command: ./service
    depends_on:
      - users_db

  users_db:
    container_name: users_db
    image: mongo:latest
    ports:
      - 27017:27017

  # ==========================================================================

  rooms:
    container_name: rooms
    build: ./services/rooms
    environment:
      ROOMS_HTTP_PORT: "8020"
      ROOMS_HTTP_PONG_TIMEOUT: "30s"

      ROOMS_USERS_GRPC_URL: "users:8011"
      ROOMS_REDIS_URL: "rooms_cache:6379"
      ROOMS_REDIS_PASSW: ""
    ports:
      - 8020:8020
    command: ./service
    depends_on:
      - rooms_cache

  rooms_cache:
    container_name: rooms_cache
    image: redislabs/redismod
    ports:
      - 6379:6379
