events {}

http {
  server {
    listen 8000;

    location /users/ {
      add_header Access-Control-Allow-Origin http://localhost:5173 always;
      add_header Access-Control-Allow-Credentials true always;

      proxy_pass http://users:8000/;
    }
  }
}
